version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=ShareIt

  db:
    image: postgres:14
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ShareIt
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin