version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT-SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  db:
    image: postgres:13.7-alpine
    container_name: shareit
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin